//! Secure in-memory credential store backed by AES-256-GCM.
//!
//! Credentials are encrypted at rest inside the process heap using a
//! per-session ephemeral key.  On process exit the key material and all
//! ciphertexts are zeroed automatically via [`ZeroizeOnDrop`].
//!
//! # Design
//! - Encryption: AES-256-GCM (authenticated encryption, 96-bit nonce)
//! - Key: random 256-bit session key generated by the OS CSPRNG at startup
//! - Zeroization: all sensitive byte buffers implement `ZeroizeOnDrop`
//!
//! # Example
//! ```rust
//! use claw_pal::credential_store::CredentialStore;
//!
//! let store = CredentialStore::new_session();
//! store.set("anthropic_api_key", "sk-ant-...").unwrap();
//! let secret = store.get("anthropic_api_key").unwrap();
//! println!("{}", secret.expose());
//! ```

use aes_gcm::{
    aead::{Aead, AeadCore, OsRng},
    Aes256Gcm, KeyInit,
};
use dashmap::DashMap;
use std::fmt;
use zeroize::{Zeroize, ZeroizeOnDrop};

/// Errors produced by [`CredentialStore`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum CredentialError {
    /// Key not found in the store.
    NotFound,
    /// Encryption operation failed.
    EncryptionFailed,
    /// Decryption operation failed (wrong key or tampered ciphertext).
    DecryptionFailed,
    /// The decrypted bytes are not valid UTF-8.
    InvalidUtf8,
}

impl fmt::Display for CredentialError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            CredentialError::NotFound => write!(f, "credential not found"),
            CredentialError::EncryptionFailed => write!(f, "credential encryption failed"),
            CredentialError::DecryptionFailed => write!(f, "credential decryption failed"),
            CredentialError::InvalidUtf8 => write!(f, "decrypted credential is not valid UTF-8"),
        }
    }
}

impl std::error::Error for CredentialError {}

/// An encrypted credential entry stored inside [`CredentialStore`].
///
/// Both the nonce and ciphertext are zeroed when dropped.
#[derive(ZeroizeOnDrop)]
struct EncryptedEntry {
    /// 96-bit (12-byte) AES-GCM nonce — unique per entry.
    nonce: [u8; 12],
    /// AES-256-GCM ciphertext (includes 128-bit authentication tag).
    ciphertext: Vec<u8>,
}

/// A decrypted secret string that is zeroed when dropped.
///
/// The contained `String` is zeroed on drop via [`ZeroizeOnDrop`].
/// Use [`SecretString::expose`] to access the plaintext temporarily.
#[derive(ZeroizeOnDrop)]
pub struct SecretString(#[zeroize(skip)] String);

impl SecretString {
    fn new(s: String) -> Self {
        Self(s)
    }

    /// Expose the plaintext value for a single use.
    ///
    /// Callers should avoid storing the returned reference or cloning it into
    /// a long-lived variable.
    pub fn expose(&self) -> &str {
        &self.0
    }
}

impl fmt::Debug for SecretString {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("SecretString(<redacted>)")
    }
}

/// The AES-256-GCM session key stored in a zeroize-on-drop wrapper.
#[derive(ZeroizeOnDrop)]
struct SessionKey(#[zeroize(skip)] Aes256Gcm);

/// AES-256-GCM encrypted in-memory credential store.
///
/// Create one instance per process (or per security domain) and share it via
/// `Arc<CredentialStore>`.  All methods take `&self` so concurrent access is
/// safe — the underlying [`DashMap`] handles locking internally.
pub struct CredentialStore {
    /// Per-session AES-256-GCM cipher (ephemeral key, never persisted).
    cipher: SessionKey,
    /// Map from logical key name to the encrypted entry.
    store: DashMap<String, EncryptedEntry>,
}

impl CredentialStore {
    /// Create a new store with a fresh random session key.
    ///
    /// The key is generated from the OS CSPRNG and never leaves this struct.
    pub fn new_session() -> Self {
        let key = Aes256Gcm::generate_key(OsRng);
        Self {
            cipher: SessionKey(Aes256Gcm::new(&key)),
            store: DashMap::new(),
        }
    }

    /// Encrypt and store a credential.
    ///
    /// Each call generates a new random nonce, so the same `value` stored
    /// twice will produce two different ciphertexts.
    ///
    /// # Errors
    /// Returns [`CredentialError::EncryptionFailed`] if the underlying cipher
    /// fails (should not happen with a well-formed key).
    pub fn set(&self, key: &str, value: &str) -> Result<(), CredentialError> {
        let nonce = Aes256Gcm::generate_nonce(OsRng);
        let ciphertext = self
            .cipher
            .0
            .encrypt(&nonce, value.as_bytes())
            .map_err(|_| CredentialError::EncryptionFailed)?;

        self.store.insert(
            key.to_string(),
            EncryptedEntry {
                nonce: nonce.into(),
                ciphertext,
            },
        );
        Ok(())
    }

    /// Decrypt and return the stored credential.
    ///
    /// The returned [`SecretString`] holds the plaintext only for the duration
    /// of the caller's use; it is zeroed when dropped.
    ///
    /// # Errors
    /// - [`CredentialError::NotFound`] — no entry with this key
    /// - [`CredentialError::DecryptionFailed`] — authentication tag mismatch
    /// - [`CredentialError::InvalidUtf8`] — decrypted bytes are not UTF-8
    pub fn get(&self, key: &str) -> Result<SecretString, CredentialError> {
        let entry = self.store.get(key).ok_or(CredentialError::NotFound)?;

        let nonce = aes_gcm::Nonce::from_slice(&entry.nonce);
        let mut plaintext = self
            .cipher
            .0
            .decrypt(nonce, entry.ciphertext.as_slice())
            .map_err(|_| CredentialError::DecryptionFailed)?;

        let s = String::from_utf8(plaintext.clone()).map_err(|_| {
            plaintext.zeroize();
            CredentialError::InvalidUtf8
        })?;
        plaintext.zeroize();

        Ok(SecretString::new(s))
    }

    /// Remove a credential from the store.
    ///
    /// Returns `true` if the key existed and was removed.
    pub fn remove(&self, key: &str) -> bool {
        self.store.remove(key).is_some()
    }

    /// Returns `true` if the store contains the given key.
    pub fn contains(&self, key: &str) -> bool {
        self.store.contains_key(key)
    }

    /// Return the number of credentials currently stored.
    pub fn len(&self) -> usize {
        self.store.len()
    }

    /// Return `true` if the store is empty.
    pub fn is_empty(&self) -> bool {
        self.store.is_empty()
    }
}

impl fmt::Debug for CredentialStore {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("CredentialStore")
            .field("entries", &self.store.len())
            .finish()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn store() -> CredentialStore {
        CredentialStore::new_session()
    }

    #[test]
    fn test_set_and_get_roundtrip() {
        let s = store();
        s.set("api_key", "sk-secret-123").unwrap();
        let got = s.get("api_key").unwrap();
        assert_eq!(got.expose(), "sk-secret-123");
    }

    #[test]
    fn test_get_not_found() {
        let s = store();
        assert_eq!(s.get("missing").unwrap_err(), CredentialError::NotFound);
    }

    #[test]
    fn test_overwrite_key() {
        let s = store();
        s.set("k", "v1").unwrap();
        s.set("k", "v2").unwrap();
        assert_eq!(s.get("k").unwrap().expose(), "v2");
    }

    #[test]
    fn test_multiple_keys_independent() {
        let s = store();
        s.set("a", "alpha").unwrap();
        s.set("b", "beta").unwrap();
        assert_eq!(s.get("a").unwrap().expose(), "alpha");
        assert_eq!(s.get("b").unwrap().expose(), "beta");
    }

    #[test]
    fn test_empty_value() {
        let s = store();
        s.set("empty", "").unwrap();
        assert_eq!(s.get("empty").unwrap().expose(), "");
    }

    #[test]
    fn test_unicode_value() {
        let s = store();
        s.set("emoji", "🔐密钥").unwrap();
        assert_eq!(s.get("emoji").unwrap().expose(), "🔐密钥");
    }

    #[test]
    fn test_same_value_different_ciphertexts() {
        // Two insertions of the same value must produce different ciphertexts
        // because each gets a fresh random nonce.
        let s = store();
        s.set("k1", "secret").unwrap();
        s.set("k2", "secret").unwrap();
        let e1 = s.store.get("k1").unwrap();
        let e2 = s.store.get("k2").unwrap();
        // Different nonces → different ciphertexts
        assert_ne!(e1.nonce, e2.nonce);
        assert_ne!(e1.ciphertext, e2.ciphertext);
    }

    #[test]
    fn test_remove() {
        let s = store();
        s.set("k", "v").unwrap();
        assert!(s.remove("k"));
        assert!(!s.remove("k"));
        assert_eq!(s.get("k").unwrap_err(), CredentialError::NotFound);
    }

    #[test]
    fn test_contains() {
        let s = store();
        assert!(!s.contains("k"));
        s.set("k", "v").unwrap();
        assert!(s.contains("k"));
        s.remove("k");
        assert!(!s.contains("k"));
    }

    #[test]
    fn test_len_and_is_empty() {
        let s = store();
        assert!(s.is_empty());
        assert_eq!(s.len(), 0);
        s.set("a", "1").unwrap();
        s.set("b", "2").unwrap();
        assert_eq!(s.len(), 2);
        assert!(!s.is_empty());
    }

    #[test]
    fn test_secret_string_debug_redacted() {
        let secret = SecretString::new("super-secret".to_string());
        assert_eq!(format!("{:?}", secret), "SecretString(<redacted>)");
    }

    #[test]
    fn test_credential_error_display() {
        assert_eq!(CredentialError::NotFound.to_string(), "credential not found");
        assert_eq!(
            CredentialError::EncryptionFailed.to_string(),
            "credential encryption failed"
        );
        assert_eq!(
            CredentialError::DecryptionFailed.to_string(),
            "credential decryption failed"
        );
        assert_eq!(
            CredentialError::InvalidUtf8.to_string(),
            "decrypted credential is not valid UTF-8"
        );
    }

    #[test]
    fn test_store_debug() {
        let s = store();
        s.set("k", "v").unwrap();
        let dbg = format!("{:?}", s);
        assert!(dbg.contains("CredentialStore"));
        assert!(dbg.contains("entries"));
        // Must NOT leak ciphertext or key material
        assert!(!dbg.contains("sk-"));
    }
}
